### PR TITLE
Support zuul-web ssl

### PR DESCRIPTION
**Pull request by wangxiyuan**
Add https support for zuul-web

### CODE REVIEW

**Comment by wangxiyuan** [comment]
recheck

**Comment by wangxiyuan** [comment]
recheck

**Comment by huangtianhua** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
recheck

**Review by bzhaoopenstack — APPROVED** [review]
lgtm

**Review by bzhaoopenstack — APPROVED** [review]
looks it's ready

**Pull request merged**
