### PR TITLE
Add experimental flag for plugin

### PR DESCRIPTION
**Pull request by Yikun**
openlab check [--type default]
will only check the non-experimental plugin.

openlab check [--type all]
will run the all plugins

openlab check [--type job|nodepool]
will run the all plugins under job|nodepool

### CODE REVIEW

**Comment by wangxiyuan** [comment]
what happened to `network` and `sg` to mark them  experimental ?

**Comment by Yikun** [comment]
@wangxiyuan the network and sg in our env are not ready to pass the "openlab-xxx" format check. So, I mark it as experimental and in order to make the lab check periodic job works well in env.

**Review by wangxiyuan — APPROVED** [review]

**Comment by Yikun** [comment]
@theopenlab/dev-core

**Review by bzhaoopenstack — APPROVED** [review]
LGTM

**Pull request merged**
