### PR TITLE
HA improvement

### PR DESCRIPTION
**Pull request by wangxiyuan**
1. We aim to make HA healthchecker be a service, so that the first
step is to remove jinjia format.
2. Fix ssl var indent.
3. add wrapt requirement.
4. Use apscheduler instead of systemd timer.

Related-Bug: theopenlab/openlab#218

### CODE REVIEW

**Comment by wangxiyuan** [comment]
recheck

**Review by huangtianhua — APPROVED** [review]
LGTM

**Review by bzhaoopenstack — APPROVED** [review]
gg

**Review by kiwik — APPROVED** [review]
LGTM

**Pull request merged**
